language: node_js
node_js:
 - 'lts/*'

 branches:
  only:
  - main

before_install:
 - export TZ='Asia/Shanghai' # 设置时区

cache:
 directories:
  - node_modules
 yarn: true

 install:
- yarn

script:
- yarn: build

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist
target-branch: gh-pages
verbose: true
on:
 branch: main
